83 m2 add hlsjs player to demo app
montevideo-tech/cmcd-validator pull request #149
Opened 2023-04-04 16:57 UTC by mcamardon

2023-04-04 19:00 UTC, adriansqualabs approved these changes

2023-04-10 14:33 UTC, JoaquinBCh requested changes

2023-04-10 14:33 UTC, JoaquinBCh commented on packages/cmcd-validator-demo-app/src/components/Players/Hls/Hls.jsx
> +  return <video ref={videoRef} manifestURI={manifestURI} autoPlay={autoPlay} controls/>;
maybe we can we add an alert for that

2023-04-10 20:43 UTC, adriansqualabs approved these changes

2023-04-13 21:09 UTC, JoaquinBCh approved these changes

2023-04-13 21:09 UTC, merged