171 m2 improve demo app add id to the request showed
montevideo-tech/cmcd-validator pull request #183
Opened 2023-04-21 16:09 UTC by mcamardon

2023-04-21 17:38 UTC, coatesjuan commented on packages/cmcd-validator-demo-app/src/App.jsx
> +      console.log(action.payload)
Erase console.log

2023-04-25 16:55 UTC, coatesjuan approved these changes

2023-04-25 16:58 UTC, JoaquinBCh requested changes

2023-04-26 15:00 UTC, CamiloBorba09 approved these changes

2023-04-26 15:10 UTC, JoaquinBCh approved these changes

2023-04-26 15:11 UTC, merged