142 m2 add possibility to select a manifest from a list
montevideo-tech/cmcd-validator pull request #211
Opened 2023-05-10 20:06 UTC by coatesjuan

2023-05-11 18:11 UTC, JoaquinBCh requested changes

2023-05-11 18:11 UTC, JoaquinBCh commented on packages/cmcd-validator-demo-app/src/components/Dropdown/Dropdown.jsx
> +const SegmentedButtonDropdownsExample = (props) => {
Change the component name, the name should be equal to the folter thar contains it.

2023-05-12 14:54 UTC, JoaquinBCh approved these changes

2023-05-16 13:33 UTC, mcamardon approved these changes

2023-05-16 14:10 UTC, merged