24 m1 implement header validator
montevideo-tech/cmcd-validator pull request #53
Opened 2023-02-28 15:36 UTC by rodrigo-mira

Implement the query validator https://github.com/orgs/montevideo-tech/projects/3/views/1?pane=issue&itemId=20485767

2023-02-28 15:56 UTC, arrivillagaTomas reviewed
As a whole functionality looks good 👍 .
If we call a function `is...()` of `check...()` i'd expect it to return a boolean value, let's try and keep that.
Check the path of the files created, I believe there's a new folder structure to follow.

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/formatFunctions.js
> +export const isHeaderRepeated = (header, headers, errors) => {
this should return `true` or `false`

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/formatFunctions.js
> +export const isSeaparetedCorrectly = (keyVal, errors) => {
spell check -> `isSeparatedCorrectly`

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/formatFunctions.js
> +  }
Lets return false here

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/formatFunctions.js
> +export const isKeyRepeated = (key, keys, errors) => {
This should return `true` or `false`

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/constants.js
> +export const keyTypes = {
Check path, I believe this file already exists here src/utils/constant.js

2023-02-28 15:56 UTC, arrivillagaTomas commented on src/checkQuotes.js
> +const checkQuotes = (value) => value.indexOf('"') === 0 && value.lastIndexOf('"') === value.length - 1;
Check path, I believe this file already exists here src/utils/checkQuotes.js

2023-02-28 17:35 UTC, adriansqualabs approved these changes

2023-03-01 14:55 UTC, CamiloBorba09 requested changes

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +/* eslint-disable import/prefer-default-export */
We have to use eslint. I recommend not to disable it.

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +  if ((keyTypes[key] === 'string' && !checkQuotes(value)) || (keyTypes[key] === 'token' && checkQuotes(value))) {
Try to use cmcdTypes.string and cmcdTypes.token instead of "string" or "token" respectively.

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +  if ((keyTypes[key] === 'boolean') && value === 'true') {
cmcdTypes.boolean instead of 'boolean'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('incorrect-format', key));
use errorTypes.incorrectFormat instead of 'incorrect-format'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('incorrect-format'));
use errorTypes.incorrectFormat instead of 'incorrect-format'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('incorrect-format', key, value));
use errorTypes.incorrectFormat instead of 'incorrect-format'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +  if ((keyVal.split('=').length > 2) || ((keyVal.split('=').length === 1) && (keyTypes[keyVal] !== 'boolean'))) {
use cmcdTypes.boolean instead of 'boolean'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('incorrect-format'));
use errorTypes.incorrectFormat instead of 'incorrect-format'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('duplicated-key', key));
use errorTypes.duplicatedKey instead of 'duplicated-key'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('duplicated-header'));
use errorTypes.duplicatedHeader instead of 'duplicated-header'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('no-header'));
use errorTypes.noHeader instead of 'no-header'

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/inputValidator/headerValidator/formatFunctions.js
> +    errors.push(createError('empty-header'));
use errorTypes.emptyHeader instead of 'empty-header'.

2023-03-01 14:55 UTC, CamiloBorba09 commented on src/parser/parseHeaderToJson.js
> +export default { parseHeaderToJSON };
try to use `export default parseHeaderToJSON;` so we are consistent

2023-03-01 16:39 UTC, CamiloBorba09 approved these changes

2023-03-01 18:58 UTC, merged